# Use the official GitBucket image as the base
FROM gitbucket/gitbucket:4.38.4

# Install gnupg and sbt
RUN apt-get update && \
    apt-get install -y curl gnupg && \
    echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list && \
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | apt-key add && \
    apt-get update && \
    apt-get install -y sbt && \
    apt-get update && \
    apt-get install -y openjdk-11-jdk

# Set the working directory
WORKDIR /gitbucket
COPY . /gitbucket
RUN sbt package
