name: Create Release

#on:
#  push:
#    tags:
      - 'v*' # triggers on tags like v1.0, v2.3.4
on:
  push:
    branches:
      - build
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build war file
        run: |
          docker build -f Dockerfile-dist .
          echo "RLVERSION=$(date '+%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
#          mkdir -p release
#          zip -r release/my-artifact.zip . -x ".git/*" ".github/*"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v4.38.4.${{env.RLVERSION}}
          release_name: Release v4.38.4.${{env.RLVERSION}}
          draft: false
          prerelease: false

      - name: Upload Assets to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/scala-2.13/gitbucket_2.13-4.38.4.war
          asset_name: gitbucket_2.13-4.38.4.${{env.RLVERSION}}.war
          asset_content_type: application/zip
